### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by K4zuki** [daamien/pandoc-latex-barcode#2]
I would like to use the filter but facing error:

``` sh
 $ pandoc-latex-barcode
Traceback (most recent call last):
  File "/usr/local/bin/pandoc-latex-barcode", line 7, in <module>
    from pandoc_latex_barcode import main
  File "/usr/local/lib/python3.6/site-packages/pandoc_latex_barcode.py", line 33
    if BARCODE in elem.classes:
                              ^
TabError: inconsistent use of tabs and spaces in indentation
```

I found the pointed file mixes indents by tabs and spaces(so the error makes sense).

**Comment by K4zuki** [comment]
I used pip which pulls 1.0.8 instead of recent version described in `setup.py`
I will install from git(`pip git+https://...`) but it would be better to update pypi archives

The thread is closed.

**Comment by daamien** [comment]
@K4zuki : thanks a lot ! 

I'm reopening it until it's fixed on pypi
